services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d

  backend:
    image: chriscaro/backend-springboot:latest
    container_name: backend-springboot
    ports:
      - "8090:8080"
    depends_on:
      - mysql-db
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  frontend:
    image: chriscaro/frontend-html:latest
    container_name: frontend-html
    ports:
      - "8081:80"
    depends_on:
      - backend
